### ISSUE TITLE
Perfoming functions on individual elements within an array

### ISSUE THREAD

**Issue by ditServices** [ditServices/linear-image-processing#1]
Not sure if following code is correct: 

`
for x in rgb:
    if x.all() > 0.009031:  # CUT constant set at 500EI as per ARRI document
        print(0.009031 * math.log10(5.555556 * x.all() + 0.060939) + 0.384493)
        print("Cond. 1")
   else:
        print(5.506188 * x.any() + 0.092800)
        print("Cond. 2")
`

Where rgb is an array of linear rgb values, I am not sure if x.all() is the correct function to reference each element.

**Comment by htjb** [comment]
.all() tests if the condition is true for all of the elements along an array. So it depends what you want to do.

If you want to test each element in the array and the rgb array is 1D with a given length(numberof entries in the array) I would write a for loop like this...

for i in range(len(rgb)):
     if rgb[i] >0.009031:
          print(0.009031* math.log10(5.555556*x[i] +0.060939)+0.384493)
          print('cond. 1')
     else:
          print(... * x[i] + ...)

Alternatively I think you can write....

for x in rgb:
     if x >0.009031:
          print(0.009031* math.log10(5.555556*x +0.060939)+0.384493)
          print('cond. 1')
     else:
          print(... * x + ...)

which is essentially what you have done but without the .any() and .all()'s. They are unnecessary because you are defining x as an element of the array rgb. .all() and .any() should only work on an array any way not on an element so I imagine that bit of code you have throws up an error but I'm not sure?

Personally I prefer indexing elements like for i in range(len(rgb)): ....x[i].... It can help keep track of what you are doing when you deal with higher dimensional arrays.

**Comment by ditServices** [comment]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
This is what happened before i decided to use .any / .all()
